import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from '../context/AuthContext'

export const metadata: Metadata = {
  title: "Productivity App",
  description: "Generated by Niya",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
